(function (root) {
  "use strict";

  root.VNRevivalInterfacePresets = Object.freeze({
    en: Object.freeze({
      language: "Language", translate: "Translate", cancel: "Cancel",
      autoHint: "If translation glitches, turn off Auto translate below.", retryFailed: "Retry failed",
      privacyText: "Visible game text is sent to the selected translation service. Save slots and input fields are excluded.",
      allowAuto: "Allow auto-translate", manualOnly: "Manual only", translationService: "Translation service",
      modelParameters: "Model parameters", reasoningEffort: "Reasoning effort", parallelRequests: "Parallel requests",
      providerDefault: "Provider default", none: "None", minimal: "Minimal", low: "Low", medium: "Medium",
      high: "High", extraHigh: "Extra high", maximum: "Maximum", advanced: "Advanced",
      hideAdvanced: "Hide advanced", cacheNotice: "After making changes, delete the cache below to retranslate text that was already translated.",
      systemPrompt: "System prompt", hideSystemPrompt: "Hide system prompt", restoreDefault: "Restore default",
      glossary: "Glossary", hideGlossary: "Hide glossary", glossaryPlaceholder: "One entry per line: source = translation",
      autoTranslate: "Auto translate", on: "On", off: "Off", cache: "Cache", log: "Log", delete: "Delete", copyLog: "Copy log",
      projectWebsite: "Project website:", collapse: "Collapse translator", expand: "Expand translator",
      interfaceToggleTitle: "Translate this panel using a built-in preset for the selected language.",
      presetTitle: "Select a provider profile, or Custom for your own endpoint.",
      baseURLTitle: "API endpoint used to list models and send translation requests.",
      keyTitle: "Saved securely for this Base URL and never stored in the game.",
      modelTitle: "Open the list to refresh available models, or choose manual entry.",
      reasoningTitle: "Controls how much reasoning the model may use. Higher values can be slower.",
      parallelTitle: "Number of translation requests sent at once. Higher is faster but may hit rate limits.",
      advancedTitle: "Show system prompt and glossary settings.",
      promptTitle: "Edit the instructions sent to the AI before each text fragment.",
      resetTitle: "Replace the custom prompt with the built-in default.",
      promptInputTitle: "Instructions sent to the AI before each text fragment.",
      glossaryTitle: "Set preferred translations that are appended to the system prompt.",
      glossaryInputTitle: "Add one source-to-translation mapping per line.",
      autoTitle: "Translate newly visible or changed game text automatically.",
      cacheDeleteTitle: "Delete all cached translations and the local service log. Other settings stay unchanged.",
      copyLogTitle: "Copy the local service log to the clipboard.",
      chooseModel: "Choose a model…", freeModel: "Free", customModel: "Custom", enterModel: "Enter model ID manually…",
      deleteConfirm: "Delete all cached translations and the local service log?", cacheDeleted: "Cache and log deleted", cacheDeleteFailed: "Could not completely delete cache and log",
      logCopied: "Log copied", logTailCopied: "Latest 2 MB of log copied", logCopyFailed: "Could not copy log"
    }),
    ru: Object.freeze({
      language: "Язык", translate: "Перевести", cancel: "Отменить",
      autoHint: "Если перевод работает с ошибками, отключите автоперевод ниже.", retryFailed: "Повторить ошибки",
      privacyText: "Видимый текст игры отправляется выбранному сервису перевода. Слоты сохранения и поля ввода исключены.",
      allowAuto: "Разрешить автоперевод", manualOnly: "Только вручную", translationService: "Сервис перевода",
      modelParameters: "Параметры модели", reasoningEffort: "Глубина рассуждений", parallelRequests: "Параллельные запросы",
      providerDefault: "Как у провайдера", none: "Нет", minimal: "Минимальная", low: "Низкая", medium: "Средняя",
      high: "Высокая", extraHigh: "Очень высокая", maximum: "Максимальная", advanced: "Дополнительно",
      hideAdvanced: "Скрыть дополнительные", cacheNotice: "После изменений удалите кэш ниже, чтобы уже переведённый текст перевёлся заново.",
      systemPrompt: "Системный промт", hideSystemPrompt: "Скрыть системный промт", restoreDefault: "Вернуть стандартный",
      glossary: "Словарь", hideGlossary: "Скрыть словарь", glossaryPlaceholder: "Одна строка: исходник = перевод",
      autoTranslate: "Автоперевод", on: "Вкл.", off: "Выкл.", cache: "Кэш", log: "Лог", delete: "Удалить", copyLog: "Копировать лог",
      projectWebsite: "Сайт проекта:", collapse: "Свернуть переводчик", expand: "Развернуть переводчик",
      interfaceToggleTitle: "Переводить эту панель встроенным пресетом выбранного языка.",
      presetTitle: "Выберите профиль провайдера или Custom для своего endpoint.",
      baseURLTitle: "API endpoint для получения моделей и отправки запросов перевода.",
      keyTitle: "Безопасно хранится для этого Base URL и не сохраняется в игре.",
      modelTitle: "Откройте список для обновления моделей или выберите ручной ввод.",
      reasoningTitle: "Определяет объём рассуждений модели. Высокие значения могут работать медленнее.",
      parallelTitle: "Число одновременных запросов. Больше — быстрее, но возможен rate limit.",
      advancedTitle: "Показать системный промт и настройки словаря.",
      promptTitle: "Изменить инструкции, отправляемые ИИ перед каждым фрагментом.",
      resetTitle: "Заменить изменённый промт встроенным стандартным.",
      promptInputTitle: "Инструкции, отправляемые ИИ перед каждым фрагментом.",
      glossaryTitle: "Задать предпочтительные переводы, добавляемые к системному промту.",
      glossaryInputTitle: "Добавьте по одной паре исходник–перевод в строке.",
      autoTitle: "Автоматически переводить новый или изменённый видимый текст игры.",
      cacheDeleteTitle: "Удалить все кэшированные переводы и лог локального сервиса. Остальные настройки сохранятся.",
      copyLogTitle: "Скопировать лог локального сервиса в буфер обмена.",
      chooseModel: "Выберите модель…", freeModel: "Бесплатно", customModel: "Другая", enterModel: "Ввести ID модели вручную…",
      deleteConfirm: "Удалить все кэшированные переводы и лог локального сервиса?", cacheDeleted: "Кэш и лог удалены", cacheDeleteFailed: "Не удалось полностью удалить кэш и лог",
      logCopied: "Лог скопирован", logTailCopied: "Скопированы последние 2 МБ лога", logCopyFailed: "Не удалось скопировать лог"
    })
  });
})(typeof globalThis !== "undefined" ? globalThis : this);
