(function (root) {
  "use strict";

  root.VNRevivalInterfacePresets = Object.freeze({
    en: Object.freeze({
      language: "Language", translate: "Translate", cancel: "Cancel",
      retryFailed: "Retry translation", retryTitle: "Retry only the fragments that could not be translated.",
      progress: "Translating: {done}/{total}", alreadyTranslated: "Everything on this screen is translated.",
      retryWaiting: "{reason} Retrying in {seconds}s ({attempt}/{attempts}).",
      translationFailed: "{reason} Untranslated fragments: {count}.",
      autoPaused: "Automatic translation is paused. Fix the cause and retry.",
      requestFailed: "Could not translate the text.", requestRejected: "The service rejected the request (HTTP {status}).",
      rateLimited: "Service limit reached. Try again later.", keyRejected: "The API key was rejected. Check the saved key.",
      modelUnavailable: "This model is unavailable. Select another model.", billingRequired: "The service account has insufficient credit.",
      formatInvalid: "The service returned an invalid translation format.", connectionFailed: "Could not connect to the translation service.",
      translationCancelled: "Translation cancelled.",
      reasoningUnsupported: "This reasoning level is not supported by the model. Select Low, High, or Maximum.",
      reasoningRequiredTitle: "This model always uses reasoning. Low is the least intensive supported level; the provider default may use more tokens.",
      privacyText: "Visible game text is sent to the selected translation service. Save slots and input fields are excluded.",
      allowAuto: "Allow auto-translate", manualOnly: "Manual only", translationService: "Translation service",
      modelParameters: "Model parameters", reasoningEffort: "Reasoning effort", parallelRequests: "Parallel requests",
      providerDefault: "Provider default", none: "None", minimal: "Minimal", low: "Low", medium: "Medium",
      high: "High", extraHigh: "Extra high", maximum: "Maximum", advanced: "Advanced",
      hideAdvanced: "Hide advanced", cacheNotice: "Changes apply on the next translation. Unaffected cached translations are kept.",
      systemPrompt: "System prompt", hideSystemPrompt: "Hide system prompt", restoreDefault: "Restore default",
      glossary: "Glossary", hideGlossary: "Hide glossary", glossaryPlaceholder: "One entry per line: source = translation",
      autoTranslate: "Auto translate", on: "On", off: "Off", cache: "Cache", log: "Log", delete: "Clear cache and log", copyLog: "Copy log",
      interfaceLabel: "Translate panel interface", endpoint: "API address",
      keyPlaceholder: "API key · Enter to save", changeKey: "Change",
      keySaved: "Key saved", keyMissing: "API key required", keyOptional: "API key optional",
      keyChecking: "Checking connection…", keyUnknown: "Key status unavailable",
 collapse: "Collapse translator", expand: "Expand translator",
      interfaceToggleTitle: "Translate this panel using a built-in preset for the selected language.",
      presetTitle: "Select a provider profile, or Custom for your own endpoint.",
      baseURLTitle: "API endpoint used to list models and send translation requests.",
      keyTitle: "Saved securely for this Base URL and never stored in the game.",
      modelTitle: "Open the list to refresh available models, or choose manual entry.",
      reasoningTitle: "Controls how much reasoning the model may use. Higher values can be slower.",
      parallelTitle: "Number of translation requests sent at once. Higher is faster but may hit rate limits.",
      advancedTitle: "Show system prompt and glossary settings.",
      promptTitle: "Edit the instructions sent to the AI before each text fragment.",
      resetTitle: "Replace the custom prompt with the built-in default.",
      promptInputTitle: "Instructions sent to the AI before each text fragment.",
      glossaryTitle: "Set preferred translations that are appended to the system prompt.",
      glossaryInputTitle: "Add one source-to-translation mapping per line.",
      autoTitle: "Translate newly visible or changed game text automatically.",
      cacheDeleteTitle: "Delete all cached translations and the local service log. Other settings stay unchanged.",
      copyLogTitle: "Copy the local service log to the clipboard.",
      chooseModel: "Choose a model…", freeModel: "Free", customModel: "Custom", enterModel: "Enter model ID manually…",
      deleteConfirm: "Delete all cached translations and the local service log?", cacheDeleted: "Cache and log deleted", cacheDeleteFailed: "Could not completely delete cache and log",
      logCopied: "Log copied", logTailCopied: "Latest 2 MB of log copied", logCopyFailed: "Could not copy log"
    }),
    ru: Object.freeze({
      language: "Язык", translate: "Перевести", cancel: "Отменить",
      retryFailed: "Повторить перевод", retryTitle: "Повторить перевод только тех фрагментов, которые не удалось перевести.",
      progress: "Перевод: {done}/{total}", alreadyTranslated: "Всё на этом экране уже переведено.",
      retryWaiting: "{reason} Повтор через {seconds} с ({attempt}/{attempts}).",
      translationFailed: "{reason} Непереведённых фрагментов: {count}.",
      autoPaused: "Автоперевод приостановлен. Устраните причину и повторите перевод.",
      requestFailed: "Не удалось перевести текст.", requestRejected: "Сервис отклонил запрос (HTTP {status}).",
      rateLimited: "Достигнут лимит сервиса. Повторите позже.", keyRejected: "API-ключ отклонён. Проверьте сохранённый ключ.",
      modelUnavailable: "Модель недоступна. Выберите другую модель.", billingRequired: "На счёте сервиса недостаточно средств.",
      formatInvalid: "Сервис вернул перевод с неправильным форматом.", connectionFailed: "Не удалось подключиться к сервису перевода.",
      translationCancelled: "Перевод отменён.",
      reasoningUnsupported: "Модель не поддерживает эту глубину рассуждений. Выберите низкую, высокую или максимальную.",
      reasoningRequiredTitle: "Эта модель всегда использует рассуждения. Низкая — минимальный поддерживаемый уровень; значение провайдера по умолчанию может расходовать больше токенов.",
      privacyText: "Видимый текст игры отправляется выбранному сервису перевода. Слоты сохранения и поля ввода исключены.",
      allowAuto: "Разрешить автоперевод", manualOnly: "Только вручную", translationService: "Сервис перевода",
      modelParameters: "Параметры модели", reasoningEffort: "Глубина рассуждений", parallelRequests: "Параллельные запросы",
      providerDefault: "Как у провайдера", none: "Нет", minimal: "Минимальная", low: "Низкая", medium: "Средняя",
      high: "Высокая", extraHigh: "Очень высокая", maximum: "Максимальная", advanced: "Дополнительно",
      hideAdvanced: "Скрыть дополнительные", cacheNotice: "Изменения применятся при следующем переводе. Кэш незатронутых переводов сохранится.",
      systemPrompt: "Системный промт", hideSystemPrompt: "Скрыть системный промт", restoreDefault: "Вернуть стандартный",
      glossary: "Словарь", hideGlossary: "Скрыть словарь", glossaryPlaceholder: "Одна строка: исходник = перевод",
      autoTranslate: "Автоперевод", on: "Вкл.", off: "Выкл.", cache: "Кэш", log: "Лог", delete: "Очистить кэш и лог", copyLog: "Копировать лог",
      interfaceLabel: "Переводить интерфейс панели", endpoint: "Адрес API",
      keyPlaceholder: "API-ключ · Enter для сохранения", changeKey: "Изменить",
      keySaved: "Ключ сохранён", keyMissing: "Нужен API-ключ", keyOptional: "Ключ необязателен",
      keyChecking: "Проверка подключения…", keyUnknown: "Состояние ключа недоступно",
 collapse: "Свернуть переводчик", expand: "Развернуть переводчик",
      interfaceToggleTitle: "Переводить эту панель встроенным пресетом выбранного языка.",
      presetTitle: "Выберите профиль провайдера или Custom для своего endpoint.",
      baseURLTitle: "API endpoint для получения моделей и отправки запросов перевода.",
      keyTitle: "Безопасно хранится для этого Base URL и не сохраняется в игре.",
      modelTitle: "Откройте список для обновления моделей или выберите ручной ввод.",
      reasoningTitle: "Определяет объём рассуждений модели. Высокие значения могут работать медленнее.",
      parallelTitle: "Число одновременных запросов. Больше — быстрее, но возможен rate limit.",
      advancedTitle: "Показать системный промт и настройки словаря.",
      promptTitle: "Изменить инструкции, отправляемые ИИ перед каждым фрагментом.",
      resetTitle: "Заменить изменённый промт встроенным стандартным.",
      promptInputTitle: "Инструкции, отправляемые ИИ перед каждым фрагментом.",
      glossaryTitle: "Задать предпочтительные переводы, добавляемые к системному промту.",
      glossaryInputTitle: "Добавьте по одной паре исходник–перевод в строке.",
      autoTitle: "Автоматически переводить новый или изменённый видимый текст игры.",
      cacheDeleteTitle: "Удалить все кэшированные переводы и лог локального сервиса. Остальные настройки сохранятся.",
      copyLogTitle: "Скопировать лог локального сервиса в буфер обмена.",
      chooseModel: "Выберите модель…", freeModel: "Бесплатно", customModel: "Другая", enterModel: "Ввести ID модели вручную…",
      deleteConfirm: "Удалить все кэшированные переводы и лог локального сервиса?", cacheDeleted: "Кэш и лог удалены", cacheDeleteFailed: "Не удалось полностью удалить кэш и лог",
      logCopied: "Лог скопирован", logTailCopied: "Скопированы последние 2 МБ лога", logCopyFailed: "Не удалось скопировать лог"
    })
  });
})(typeof globalThis !== "undefined" ? globalThis : this);
